WebApplication1/Controllers/AdminController.cs
using WebApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AdminController : Controller
    {
        CNPMNC_ltEntities db = new CNPMNC_ltEntities();

        // GET: Admin
        public ActionResult Index()
        {
            if (Session["TaiKhoanAdmin"] != null)
            {
                var customer = db.KhachHang;
                return View(customer.ToList());
            }
            return RedirectToAction("Login", "LoginRegister");
        }
       
    }
}

WebApplication1/Controllers/HomePageController.cs
using WebApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        CNPMNC_ltEntities db = new CNPMNC_ltEntities();
        public ActionResult Index(string SearchString)
        {
            IQueryable<SanPham> products = db.SanPham; // db.SanPham có kiểu DbSet

            if (!string.IsNullOrEmpty(SearchString))
            {
                products = products.Where(p => p.TenSP.Contains(SearchString));
            }

            return View(products.ToList());

        }
        public ActionResult GioiThieu()
        {
            return View();
        }

       

    }
}

WebApplication1/Controllers/TKDSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TKDSController : Controller
    {
        // GET: TKDS
        CNPMNC_ltEntities db = new CNPMNC_ltEntities();
        public static string connectionString = "data source=LEANHKHOA\\SQLEXPRESS;initial catalog=CNPMNC_lt;integrated security=True";
        public ActionResult Index()
        {
            ViewBag.CountOrderDetail = db.CTDonHang.Count();
            ViewBag.CountProduct = db.SanPham.Count();
            
            TempData["TongDonHang"] = db.DonHang.Where(n => n.TinhTrang == "Đã duyệt").Count();

           TempData["TongDoanhThu"] = db.DonHang.Where(n => n.TinhTrang == "Đã duyệt" /*&& n.NgayGiao.ToString() != ""*/).Sum(n => n.TongThanhTien);
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                  
                string query = "TKSP";
                DateTime fromDate = new DateTime(2023, 08, 01);
                DateTime toDate = new DateTime(2023, 12, 31);

                List<ThongKeTheoTuanModel> model = new List<ThongKeTheoTuanModel>();

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    SqlCommand command = new SqlCommand(query, connection);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@FromDate", fromDate);
                    command.Parameters.AddWithValue("@ToDate", toDate);
                    connection.Open();
                    SqlDataReader reader = command.ExecuteReader();

                    // Xử lý dữ liệu từ SqlDataReader
                    while (reader.Read())
                    {
                        ThongKeTheoTuanModel item = new ThongKeTheoTuanModel();
                        item.TuNgay = (DateTime)reader["TuNgay"];
                        item.DenNgay = (DateTime)reader["DenNgay"];
                        item.SoHoaDon = (int)reader["SoHoaDon"];
                        item.TongDoanhThu = (decimal)reader["ToxngDoanhThu"];
                        model.Add(item);
                    }
                    reader.Close();
                }

                return View(model);
            }
        }
    }
}

WebApplication1/Views/Admin/Index.cshtml
@model IEnumerable<WebApplication1.Models.KhachHang>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="~/Style/admin.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">

</head>
<body>
    <div class="container">
        <div class="sidebar">
            <a href="@Url.Action("Index","HomePage")" class="item">
                <img class="icon" src="~/Image/icon_admin1.png" alt="">
                <div style="list-style: bold;font-weight: 600; font-size: 24px;" class="text">
                    Admin website

                </div>
            </a>
            <hr>
            <a href="@Url.Action("Index","AdminProduct")" class="item">
                <img class="icon" src="~/Image/icon_product.png" alt="">
                <div class="text">
                    Sản phẩm

                </div>
            </a>
            <a href="@Url.Action("Index","Admin")" class="item">
                <img class="icon" src="~/Image/icon_khachhang.jpg" alt="">
                <div class="text">
                    Thống tin khách hàng

                </div>
            </a>
            <a style="color:black;text-decoration:none;" href="@Url.Action("DanhSachDonHang","QlyNhapHang")" class="item">
                <img class="icon" src="~/Image/icon_bil.png" alt="">
                <div class="text">
                    Danh sách đơn hàng

                </div>
            </a>
            <a style="color:black;text-decoration:none;" href="@Url.Action("DanhSachChuaDuyet","QlyNhapHang")" class="item">
                <img class="icon" src="~/Image/icon_bill.png" alt="">
                <div class="text">
                    Chờ duyệt

                </div>
            </a>
            <a style="color:black;text-decoration:none;" href="@Url.Action("Index","AdminFavorite")" class="item">
                <img class="icon" src="~/Image/favorite1.jpg" alt="">
                <div class="text">
                    Khách hàng yêu thích

                </div>
            </a>
            <a style="color:black;text-decoration:none;" href="@Url.Action("Index","TKDS")" class="item">
                <img class="icon" src="~/Image/icon_thongke.jpg" alt="">
                <div class="text">
                    Thống kê doanh thu

                </div>
            </a>
        </div>
        <div class="nav">
            <div class="content">
                <h1>Quản lí website bán điện thoại</h1>


                <div class="content_table">
                    <table id="myTable" class="display">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Khách hàng</th>
                                <th>SDT</th>
                                <th>Giới tính</th>
                                <th>Email</th>
                                <th>Mật khẩu</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            <!-- code hiển thị data -->
                            @foreach(var item in Model)
            {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.IDUser)</td>
                                <td>@Html.DisplayFor(modelItem => item.TenKH)</td>
                                <td>@Html.DisplayFor(modelItem => item.SDT)</td>
                                <td>@Html.DisplayFor(modelItem => item.GioiTinh)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>@Html.DisplayFor(modelItem => item.MatKhau)</td>
                            </tr>
            }
                           
                        </tbody>
                    </table>
                </div>


                <!--Sử dụng thư viện chart để vẽ biểu đồ-->
                </main>

                <footer>
                    <p>Địa chỉ: 828 Sư Vạn Hạnh</p>
                    <p>Tel: +28 999 888 555</p>
                </footer>
            </div>
        </div>
    </div>

</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>


<script>

    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>