WebApplication1/Controllers/HomePageController.cs
using WebApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        CNPMNC_ltEntities db = new CNPMNC_ltEntities();
        public ActionResult Index(string SearchString)
        {
            IQueryable<SanPham> products = db.SanPham; // db.SanPham có kiểu DbSet

            if (!string.IsNullOrEmpty(SearchString))
            {
                products = products.Where(p => p.TenSP.Contains(SearchString));
            }

            return View(products.ToList());

        }
        public ActionResult GioiThieu()
        {
            return View();
        }

       

    }
}

WebApplication1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        CNPMNC_ltEntities db = new CNPMNC_ltEntities();

        // GET: Product
        public ActionResult Index(int id)
        {
            var product = db.SanPham.Find(id);
            return View(product);
        }
        public ActionResult SanPhamTheoPhanLoai(string phanloai)
        {
            // Thực hiện truy vấn SQL để lấy sản phẩm theo phân loại
            List<SanPham> products = db.SanPham.Where(p => p.PhanLoai.TenPhanLoai == phanloai).ToList();

            // Truyền danh sách sản phẩm đã lọc vào view
            return View(products);
        }
    }
}

WebApplication1/Views/Product/Index.cshtml
@model WebApplication1.Models.SanPham
@{
    ViewBag.Title = "Index";
}

@{ var formatMoney = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");}
@{
    ViewBag.Title = "Detail";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Style/style.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Style/Owl/slide.css">
    <link rel="stylesheet" href="/owl.carousel.min.css">
    <link rel="stylesheet" href="/owl.theme.default.min.css">
    <link rel="stylesheet" href="JS/StyleSilder.js">
</head>
<body>

    
    <div style="margin-bottom:20px;" class="content">
        <div class="container_content">
            <dv class="content_breadcrum">

                <ul style="padding: 0;border-bottom: 2px solid rgb(233, 226, 226);padding-bottom: 10px;margin-bottom: 15px;margin-right: 120px;" class="breadcrumbs">
                    <li> <a href="@Url.Action("Index","HomePage")">Điện thoại</a></li>
                    <li>
                        <span>></span>
                        <a href="">Điện thoại iPhone</a>
                    </li>
                </ul>


                <h4>@Model.TenSP @Model.DungLuong | Chính hãng</h4>

                <div class="content_details">
                    <div class="content_details_img">
                        <img id="mainImage" src="~/Image/@Model.AnhMoTa1" alt="">
                        <div class="content_details_img_sub">
                            <img data-image="/Image/@Model.AnhMoTa1" src="~/Image/@Model.AnhMoTa1" alt="">
                            <img data-image="/Image/@Model.AnhMinhHoa1" src="~/Image/@Model.AnhMinhHoa1" alt="">
                            <img data-image="/Image/@Model.AnhMoTa5" src="~/Image/@Model.AnhMoTa5" alt="">
                            <img data-image="/Image/@Model.AnhMoTa4" src="~/Image/@Model.AnhMoTa4" alt="">
                            <img data-image="/Image/@Model.AnhMoTa3" src="~/Image/@Model.AnhMoTa3" alt="">
                        </div>
                        <div class="content_details_policy">
                            <div class="policy">
                                <ul class="policy_list">
                                    <li>
                                        <i class="fa-solid fa-right-left"></i>
                                        <div>Hư gì đổi nấy 12 tháng tại 3360 siêu thị toàn quốc (miễn phí tháng đầu)</div>
                                    </li>
                                    <li>
                                        <i class="fa-solid fa-shield"></i>
                                        <div>Bảo hành chính hãng điện thoại 1 năm tại các trung tâm bảo hành hãng</div>
                                    </li>
                                    <li>
                                        <i class="fa-solid fa-box"></i>
                                        <div>Bộ sản phẩm gồm: Hộp, Sách hướng dẫn, Cây lấy sim, Cáp Lightning - Type C</div>
                                    </li>
                                </ul>
                            </div>

                        </div>
                        <div class="content_details_product_info">
                            <div class="product_info">
                                <img src="~/Image/@Model.AnhMoTa6" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="content_details_info">
                        <div class="content_details_info_price">
                            <h2>@Model.TenSP @Model.DungLuong , @Model.Ram</h2>
                            <span>@String.Format(formatMoney, "{0:c0}", Model.GiaBanDau)</span>
                            <h3>  @String.Format(formatMoney, "{0:c0}", Model.GiaSP)</h3>
                        </div>
                        
                        <div class="content_details_btn">
                            <a style="color:#000;font-size:15px" href="@Url.Action("AddToCart", "Cart", new {id = Model.IDSanpham })" class="add_to_cart_btn">
                                <i class="fa-solid fa-cart-shopping"></i>
                                <span>Thêm vào giỏ hàng</span>
                            </a>
                            <a style="color:#000;" href="@Url.Action("ThemMucYeuThich", "Favorite", new { IDSanPham = Model.IDSanpham })">

                                <button style="height: 42px;" class="add_to_favorite">
                                    <i class="fa-solid fa-heart"></i>
                                </button>
                            </a>
                        </div>
                        <div class="content_details_attribute_list">
                            <div class="attribute_header">
                                <i class="fa-solid fa-gears"></i>
                                <span>Thông số kỹ thuật</span>
                            </div>
                            <ul>

                                <li style="background-color: rgb(186, 190, 193);height:91px">
                                    <span style="vertical-align: middle;">Màn hình:</span>
                                    <span style="float:right;">@Model.ManHinh</span>
                                </li>
                                <li>
                                    <span>Hệ điều hành:</span>
                                    <span style="float:right;">@Model.HDH</span>
                                </li>
                                <li style="background-color: rgb(186, 190, 193);">
                                    <span>Camera sau:</span>
                                    <span style="float:right;">@Model.CameraSau</span>
                                </li>

                                <li>
                                    <span>Camera trước:</span>
                                    <span style="float:right;">@Model.CameraTruoc</span>
                                </li>
                                <li style="background-color:rgb(186, 190, 193);">
                                    <span>Chip: </span>
                                    <span style="float:right;">@Model.Chip</span>
                                </li>
                                <li>
                                    <span>RAM:</span>
                                    <span style="float:right;">@Model.Ram</span>
                                </li>
                                <li style="background-color:rgb(186, 190, 193);">
                                    <span>Dung lượng lưu trữ:</span>
                                    <span style="float:right;">@Model.DungLuong</span>
                                </li>
                                <li style="height: 91px;">
                                    <span>SIM:</span>
                                    <span style="float:right;">@Model.Sim</span>
                                </li>
                                <li style="background-color:rgb(186, 190, 193);">
                                    <span>Pin, Sạc:</span>
                                    <span style="float:right;">@Model.Pin</span>
                                </li>
                            </ul>

                        </div>
                        <div class="content_details_special_product">
                            <div class="special_product_header">
                                <i class="fa-solid fa-circle-info"></i>
                                <span>Đặc điểm nổi bật</span>
                            </div>
                            <div class="special_product_content">
                                <p>
                                    @Model.MoTaSP
                                    @* Thiết kế mới vuông vức hơn so với iPhone 12, các cạnh viền được làm phẳng. Mặt lưng được hoàn thiện bóng bẩy và bền hơn.
                                        Màn hình Super Retina XDR 6.1 inch trên iPhone 13 và 6.7 inch trên iPhone 13 Pro Max, sáng hơn, độ tương phản cao hơn. Tần số quét được nâng cấp lên 120Hz trên phiên bản Pro.Camera có nhiều cải tiến về phần cứng và xử lý ảnh. Cụm camera kép 12MP trên iPhone 13 và cụm camera ba ống kính 12MP trên bản Pro. Khả năng chụp thiếu sáng được cải thiện đáng kể.Chip A15 Bionic mới nhất, nhanh hơn 50% so với các chip Android.*@
                                </p>
                            </div>
                        </div>
                        <div class="content_details_improve_product">
                            <div class="special_product_header">
                                <i class="fa-regular fa-sun"></i>
                                <span>Chức năng cải tiến</span>
                            </div>
                            <div class="special_product_content">
                                <p>
                                    Đây là con chip mạnh nhất trên điện thoại thông minh hiện nay.Thời lượng pin tăng đáng kể so với thế hệ trước, có thể sử dụng cả ngày dài.
                                    Hỗ trợ kết nối 5G tốc độ cao. Có phiên bản bộ nhớ 1TB, lớn nhất trên điện thoại.Face ID được cải tiến, mở khóa nhanh hơn ngay cả khi đeo khẩu trang.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>


        </div>


    </div>




    <script>
        const mainImage = document.getElementById('mainImage');
        const subImages = document.querySelectorAll('.content_details_img_sub img');

        subImages.forEach(img => {
            img.addEventListener('click', function () {
                mainImage.src = this.dataset.image;
            });
        });
    </script>
    <script src="~/JS/StyleSilder.js"></script>
</body>
</html>

WebApplication1/Views/Product/SanPhamTheoPhanLoai.cshtml
@model List<WebApplication1.Models.SanPham>
@{
    ViewBag.Title = "SanPhamTheoPhanLoai";
}
@using WebApplication1.Models;
@{ var formatMoney = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");


}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Image/logo-no-background.png" type="">
    <title>Đồng hồ</title>
    <link rel="stylesheet" href="~/Style/style.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Style/slide.css">
    <link rel="stylesheet" href="~/owl.carousel.min.css">
    <link rel="stylesheet" href="~/owl.theme.default.min.css">
    <link rel="stylesheet" href="/Style/base.css">
</head>
<body>
    <div class="container_list_items">
        <div style="margin-left: 170px;">
            <div style="margin: 20px 0;" class="product_all">
                <div style="font-size: 30px;text-align: center;" class="">TẤT CẢ SẢN PHẨM</div>
            </div>
            <div style="display: flex;flex-wrap: wrap;" class="container_slider_product">

                @foreach (var item in Model)
                {
                    <div style="margin-top: 10px;height:390px;" class="element">
                        <a href="@Url.Action("Index","Product",new { id = item.IDSanpham })">
                            <div style="padding-left: 20px;" class="card">
                                <img style="width: 195px;height:231px;" class="card-img-top" src="~/Image/@item.AnhMinhHoa" alt="Card image cap">
                                <div style="margin-bottom:4px;" class="overlay">
                                    <img style="height: 235px;border-radius: 15px 15px 0 0;width: 235px;" class="overlay_img" src="~/Image/@item.AnhMoTa2" alt="">
                                </div>
                                <div style="margin-top:12px" class="card-body">
                                    <div class="product-name">
                                        <p class="card-text">@item.TenSP @item.DungLuong | Chính hãng VN/A</p>
                                    </div>
                                    <div class="card-badge">
                                        <p class="card-badge-info-items">
                                            Ram: @item.Ram
                                        </p>
                                        <p class="card-badge-info-items">
                                            @item.DungLuong
                                        </p>
                                    </div>
                                    <h5>  @String.Format(formatMoney, "{0:c0}", item.GiaSP)</h5>
                                    <a href="@Url.Action("ThemMucYeuThich", "Favorite", new { IDSanPham = item.IDSanpham })" class="love-product">
                                        @{
                                            CNPMNC_ltEntities db = new CNPMNC_ltEntities();
                                            // Kiểm tra xem sản phẩm đã có trong bảng Favorite hay chưa
                                            if (Session["TaiKhoan"] != null)
                                            {
                                                var kh = (KhachHang)Session["TaiKhoan"];
                                                var isFavorited = db.YeuThich.Any(f => f.IDSanPham == item.IDSanpham && f.IDUser == kh.IDUser);
                                                string heartIconClass = isFavorited ? "fa-solid fa-heart favorite-icon-red" : "fa-regular fa-heart";
                                                <i class="@heartIconClass"></i>
                                            }
                                        }
                                    </a>
                                </div>
                            </div>
                        </a>

                    </div>
                }

            </div>
        </div>
</body>